name: NeedZIndia
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_pro: ^1.0.0
  carousel_slider: ^3.0.0
  google_fonts: ^2.0.0
  flutter_screenutil: ^4.0.3+3
  http: ^0.13.0
  shared_preferences: ^2.0.5
  toast: ^0.1.5
  http_interceptor: ^0.4.1
  dependencies:
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.0
  connectivity: ^3.0.3
  progressive_image: ^1.0.1
  image_picker: ^0.7.3
  cached_network_image: ^2.5.1
  geolocator: ^7.0.1
  readmore: ^1.0.1
  firebase_messaging: ^10.0.0
  provider: ^5.0.0
  android_intent: ^2.0.0
  url_launcher: ^6.0.2
  location: ^4.1.1
  firebase_core: ^1.0.1
  geocoding: ^2.0.0
  new_version: ^0.2.3





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  image_path: 'assets/images/appicon.png'
  android: true
  ios: true
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/wishlist.png
    - assets/images/empty_shopping_cart.png
    - assets/images/oralcare.jpg
    - assets/images/men_cat.jpg
    - assets/images/womens_cat.jpg
    - assets/images/beauty.jpg
    - assets/images/dailyneeds.PNG
    - assets/images/washing.PNG
    - assets/images/biscuits.jpg
    - assets/images/biscuits_cat.jpg
    - assets/images/snacks.PNG
    - assets/images/chocolates.jpg
    - assets/images/t&c.PNG
    - assets/images/pdrinks.PNG
    - assets/images/real.PNG
    - assets/images/fastfood.PNG
    - assets/images/pan.png
    - assets/images/pan_cat.png
    - assets/images/circle_dn.PNG
    - assets/images/circle_bsc.PNG
    - assets/images/circle_books.PNG
    - assets/images/circle_pc.PNG
    - assets/images/circle_he.PNG
    - assets/images/circle_pcd.PNG
    - assets/images/circle_bv.PNG
    - assets/images/circle_sv.PNG
    - assets/images/Atta_Rice.jpg
    - assets/images/icon_flour.png
    - assets/images/oil_ghee.jpg
    - assets/images/pulses.jpg
    - assets/images/salt_sugar.jpg
    - assets/images/spices.jpg
    - assets/images/fast_food.JPG
    - assets/images/bc.jpg
    - assets/images/oral_care.jpg
    - assets/images/men_hygiene.jpg
    - assets/images/women_hygiene.jpg
    - assets/images/home_care.jpg
    - assets/images/Detergent_soap.jpg
    - assets/images/biscuits_grid.jpg
    - assets/images/snacks.jpg
    - assets/images/t_c.jpg
    - assets/images/p_d.jpg
    - assets/images/dove_grid.jpg
    - assets/images/ponds_grid.jpg
    - assets/images/hair_care.png
    - assets/images/soap_skin.png
    - assets/images/nestle_grid.JPG
    - assets/images/britania_grid.PNG
    - assets/images/Atta_Rice_cat.jpg
    - assets/images/icon_oil.png
    - assets/images/icon_pulses.png
    - assets/images/icon_spices.png
    - assets/images/icon_salt.png
    - assets/images/icon_detergent.jpg
    - assets/images/icon_home.jpg
    - assets/images/icon_healthcare.JPG
    - assets/images/tata_grid.jpg
    - assets/images/haldiram.JPG
    - assets/images/passport.jpg
    - assets/images/logo.ico
    - assets/images/avatar.png
    - assets/images/baby.jpg
    - assets/images/diapers.JPG
    - assets/images/diapers_cat.JPG
    - assets/images/baby_foods.JPG
    - assets/images/babyfood_cat.JPG
    - assets/images/baby_skin.JPG
    - assets/images/babyskin_cat.JPG
    - assets/images/baby_utensils.jpg
    - assets/images/babyutensil_cat.JPG
    - assets/images/appicon.png
    - assets/images/fade_image.jpg
    - assets/images/drawerpic.jpg
    - assets/images/logo.png
    - assets/images/babycat.JPG
    - assets/images/No_internet.png
    - assets/images/Somethingwentwrong.jpeg
    - assets/images/success.png
    - assets/images/coupon.png
    - assets/images/passportimg.jpg
    - assets/images/noresultsfound.jpg
    - assets/images/verified.png
    - assets/images/logo2.ico
    - assets/images/doctor.PNG
    - assets/images/checkup_cat.jpg
    - assets/images/icon_deo&perfumes.jpg
    - assets/images/logo_small.png
    - assets/images/aashirvaad_brand.jpg
    - assets/images/maggi_brand.png
    - assets/images/dabur_brand.png
    - assets/images/himalaya_brand.png
    - assets/images/britania_brand.png
    - assets/images/emami_brand.png
    - assets/images/dove_brand.png
    - assets/images/nestle_brand.png
    - assets/images/cadbury_brand.png
    - assets/images/Popular_brands.jpg
    - assets/images/Household_supplies.jpg
    - assets/images/Personal_care.jpg
    - assets/images/services_back.jpg
    - assets/images/loading.gif
    - assets/images/Electronics_cat.JPG
    - assets/images/Pooja_Needs_cat.JPG
    - assets/images/Dry_Fruits_cat.JPG
    - assets/images/Next_day_delivery.JPG
    - assets/images/AttaRiceTile.jpg
    - assets/images/OilGheeTile.jpg
    - assets/images/FloursTile.jpg
    - assets/images/PulsesTile.jpg
    - assets/images/SaltSugarTile.jpg
    - assets/images/SpicesTile.jpg
    - assets/images/FastFoodTile.jpg
    - assets/images/DryFruitTile.jpg
    - assets/images/PoojaTile.jpg
    - assets/images/Slider.jpg
    - assets/images/SoapSkinTile.JPG
    - assets/images/OralCareTile.JPG
    - assets/images/HairCareTile.JPG
    - assets/images/DeosTile.JPG
    - assets/images/MenHygieneTile.JPG
    - assets/images/WomenHygieneTile.JPG
    - assets/images/DetergentTile.JPG
    - assets/images/HomeCareTile.JPG
    - assets/images/HealthCareTile.JPG
    - assets/images/BiscuitsTile.jpg
    - assets/images/SnacksTile.jpg
    - assets/images/ChocolatesTile.jpg
    - assets/images/TeaTile.jpg
    - assets/images/ProteinDrinksTile.jpg
    - assets/images/RefreshmentsTile.jpg
    - assets/images/requestSuccess.png
    - assets/images/Durga_Puja_Sale.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
